plot(dt_sub$date_time,dt_sub$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(dt_sub$date_time, dt_sub$Sub_metering_2, type="l", col="red")
lines(dt_sub$date_time, dt_sub$Sub_metering_3, type="l", col="blue")
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),cex=.75,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), xjust=.5)
dev.copy(png, file="Plot3.png")
dev.off()