par(mfrow = c(2, 2),oma = c(0, 0, 2, 0), mar=c(2.1,4.1,3.1,2.1))
plot(Global_active_power ~ date_time, dt_sub, type="l", ylab="Global Active Power (kilowatts)", xlab="")
plot(Voltage ~ date_time, dt_sub, type="l", ylab="Voltage", xlab="datetime")
plot(dt_sub$date_time,dt_sub$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(dt_sub$date_time, dt_sub$Sub_metering_2, type="l", col="red")
lines(dt_sub$date_time, dt_sub$Sub_metering_3, type="l", col="blue")
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),cex=.5,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), xjust=.5, bty="n")
plot(Global_reactive_power ~ date_time, dt_sub, type="l", xlab="datetime")
dev.copy(png, file="Plot4.png")
dev.off()